config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'articles#index'
  resources :articles

end

app/models/article.rb
require 'page'

class Article < ActiveRecord::Base
  belongs_to :user
  before_create :extract_text

  validates_presence_of :user, :url

  default_scope { where("text <> ''") }

  WORDS_IN_SHORT_TEXT = 50

  def short_text
    text.split.first(WORDS_IN_SHORT_TEXT).join(' ')
  end

  private
  def extract_text
    unless text
      begin
        # Note: Ideally failed articles should be handled by a worker. The worker
        # will retry fetch text of failed articles. Also we should also show a
        # separate listing of failed articles to user.
        page = Page.new(url)
        self.text = page.text
        self.title = page.title
      rescue Exception => ex
        errors.add(:url, 'Failed to fetch text from article url')
        Rails.logger.error("Failed to extract text from url #{url} Exception #{ex.message}")
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  has_many :articles

  attr_accessor :login
  validates :username,
  :presence => true,
  :uniqueness => {
    :case_sensitive => false
  }

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = current_user.articles
  end

  def create
    new_article = Article.create(url: params[:article][:url], user: current_user)
    redirect_to(articles_path, flash: { error: new_article.errors.full_messages.join(' ') })
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <%= simple_form_for Article.new, html: { class: 'navbar-form navbar-left' } do |f| %>
      <div class="form-group">
        <%= f.input :url, placeholder: 'Paste link', class: 'form-control' %>
        <%= f.button :submit, class: 'btn btn-default' %>
      </div>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to("Sign out", destroy_user_session_path, method: :delete) %></li>
    </ul>
  </div>
</nav>
<%= flash[:error] %>
<% @articles.each do |article| %>
<div class="list-group">
  <%= link_to(article_path(article), class: 'list-group-item active') do %>
    <h4 class="list-group-item-heading"><%= article.title %></h4>
    <p class="list-group-item-text"><%= article.short_text %></p>
  <% end %>
</div>
<% end %>

app/views/articles/show.html.erb
<div id="reader-container" >
  <div class="well well-sm word-container">word</div>
  <ul class="nav nav-pills">
    <li role="presentation">
      <button id="start-reading-button" type="button" class="btn btn-default" aria-label="Left Align">Read
        <span aria-hidden="true" title="Read"></span>
      </button>
    <li role="presentation">
      <button id="glyphicon-resume-button" type="button" class="btn btn-default" aria-label="Left Align">Resume
        <span class="glyphicon glyphicon-play" aria-hidden="true" title="Resume"></span>
      </button>
    </li>
    <li role="presentation">
      <button id="glyphicon-pause-button" type="button" class="btn btn-default" aria-label="Left Align">Pause
        <span class="glyphicon glyphicon-pause" aria-hidden="true" title="Pause"></span>
      </button>
    </li>
  </ul>
  <div class="reading-speed btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <span class="selection" value="50">50wpm</span><span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><a href="#" id="5wpm" value=5>5wpm</a></li>
      <li><a href="#" id="50wpm" value=50>50wpm</a></li>
      <li><a href="#" id="100wpm" value=100>100wpm</a></li>
      <li><a href="#" id="150wpm" value=150>150wpm</a></li>
      <li><a href="#" id="200wpm" value=200>200wpm</a></li>
      <li><a href="#" id="250wpm" value=250>250wpm</a></li>
      <li><a href="#" id="300wpm" value=300>300wpm</a></li>
    </ul>
  </div>
  <div class="color-scheme btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
    <span class="selection" value="black_on_white">Black on White</span><span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><a href="#" id="black_on_white" value="black_on_white">Black on White</a></li>
      <li><a href="#" id="random" value="random">random</a></li>
    </ul>
  </div>
  <div class="well well-lg">
    <%= @article.text %>
  </div>
  <input type="hidden" id="notification-channel" value=<%= "user_#{Rails.env}_#{current_user.id}"%>>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Reader</title>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script src="//js.pusher.com/2.2/pusher.min.js"></script>
  <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
  <script>
    var Reader = {
      config: {
        coloring_service_url: "<%= Rails.configuration.coloring_service['url']%>",
      }
    };
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>